name: 'Release'

on:
    push:
        branches:
            - main
            - master

jobs:
    check-package-version:
        name: Check package version and detect an update
        runs-on: ubuntu-20.04
        outputs:
            repo-version: ${{ steps.check-package-version.outputs.repo-version }}
            published-version: ${{ steps.check-package-version.outputs.published-version }}
            is-unpublished-version: ${{ steps.check-package-version.outputs.is-unpublished-version }}
        steps:
            - name: Checkout the repository
              uses: actions/checkout@v2

            - name: Check package version and detect an update
              id: check-package-version
              uses: PostHog/check-package-version@v1

    release:
        name: Publish release if new version
        runs-on: ubuntu-20.04
        needs: check-package-version
        if: needs.check-package-version.outputs.is-unpublished-version == 'true'
        env:
            REPO_VERSION: ${{ needs.check-package-version.outputs.repo-version }}
            PUBLISHED_VERSION: ${{ needs.check-package-version.outputs.published-version }}
        steps:
            - name: Checkout the repository
              uses: actions/checkout@v2
              with:
                  fetch-depth: 0

            - name: Set up Node 14
              uses: actions/setup-node@v2
              with:
                  node-version: 14
                  registry-url: https://registry.npmjs.org

            - name: Install dependencies
              run: yarn --frozen-lockfile

            - name: Publish the package in the npm registry
              run: npm publish --access public
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

            - name: Create GitHub release
              uses: actions/create-release@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  tag_name: v${{ env.REPO_VERSION }}
                  release_name: ${{ env.REPO_VERSION }}
